[package]
name = "zipatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "2.2.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
memmap2 = "0.5.0"