name: Check Pull Request
on: [pull_request, push]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install JS deps
        run: yarn --cwd ${{ github.workspace }}/src/gui install
      - name: Build JS
        run: yarn --cwd ${{ github.workspace }}/src/gui build
        
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ${{ github.workspace }}/src/Cargo.toml
